### ISSUE TITLE
improvements to documentation

### ISSUE THREAD

**Issue by markdowney** [aichaos/rivescript.com#1]
Hey, thanks for your work on RiveScript.
As I've been using the documentation page more frequently, here are a couple suggestions :
- add a direct link to the documentation page in the header (https://www.rivescript.com/docs/tutorial)
- add a side-menu to the documentation page (akin to http://www.mkdocs.org/)

Also, the repo's current setup is not optimal for contributions since the installation is not straight forward.

**Comment by kirsle** [comment]
- The documentation link is called "Learn" on the top nav and goes to a page that links to the tutorial and the Try Online page.
  - I could rename it from "Learn" to "Documentation". The [tech spec](https://github.com/aichaos/rivescript-wd) could also be linked to from this page.
  - Or, call it "Documentation" which is a direct link to the tutorial and add a new "Try It" link that's a direct link to the Try Online page. This would make the `/learn` URL obsolete.
- The tutorial is in need of some reformatting in general. It's a Markdown doc converted over from Perl POD format, and I need to update my CMS to add support for generating a table of contents. I'm tracking that here: https://github.com/kirsle/rophako/issues/1

**Comment by kirsle** [comment]
I added a left side navigation to the tutorial page: https://www.rivescript.com/docs/tutorial

The navigation list is long and can't fit on screen all at once, so I made it so the left nav scrolls normally until the bottom is about 300px from the top of the screen, and then it pops out into a fixed left nav. While it's in the fixed mode, the bottom of the nav is cut off, which makes navigating it a little tricky, but a "Back to Top" link appears that scrolls to the top (thus reattaching the nav to the page) and you can then scroll it and click the lower links.
